"""init_er

Revision ID: cd7662f9d692
Revises: 
Create Date: 2026-02-01 14:14:23.274766

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7662f9d692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('pais', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodegas_creado_en'), 'bodegas', ['creado_en'], unique=False)
    op.create_index(op.f('ix_bodegas_eliminado_en'), 'bodegas', ['eliminado_en'], unique=False)
    op.create_index(op.f('ix_bodegas_nombre'), 'bodegas', ['nombre'], unique=False)
    op.create_index(op.f('ix_bodegas_pais'), 'bodegas', ['pais'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=32), nullable=False),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_creado_en'), 'clientes', ['creado_en'], unique=False)
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.create_index(op.f('ix_clientes_eliminado_en'), 'clientes', ['eliminado_en'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_creado_en'), 'productos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_productos_eliminado_en'), 'productos', ['eliminado_en'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('puertos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('pais', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puertos_creado_en'), 'puertos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_puertos_eliminado_en'), 'puertos', ['eliminado_en'], unique=False)
    op.create_index(op.f('ix_puertos_nombre'), 'puertos', ['nombre'], unique=False)
    op.create_index(op.f('ix_puertos_pais'), 'puertos', ['pais'], unique=False)
    op.create_table('envios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('numero_guia', sa.String(length=64), nullable=False),
    sa.Column('tipo_envio', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envios_cliente_id'), 'envios', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_envios_creado_en'), 'envios', ['creado_en'], unique=False)
    op.create_index(op.f('ix_envios_eliminado_en'), 'envios', ['eliminado_en'], unique=False)
    op.create_index(op.f('ix_envios_numero_guia'), 'envios', ['numero_guia'], unique=True)
    op.create_index(op.f('ix_envios_producto_id'), 'envios', ['producto_id'], unique=False)
    op.create_index(op.f('ix_envios_tipo_envio'), 'envios', ['tipo_envio'], unique=False)
    op.create_table('envios_maritimos',
    sa.Column('envio_id', sa.Integer(), nullable=False),
    sa.Column('puerto_id', sa.Integer(), nullable=False),
    sa.Column('numero_flota', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.ForeignKeyConstraint(['puerto_id'], ['puertos.id'], ),
    sa.PrimaryKeyConstraint('envio_id')
    )
    op.create_index(op.f('ix_envios_maritimos_puerto_id'), 'envios_maritimos', ['puerto_id'], unique=False)
    op.create_table('envios_terrestres',
    sa.Column('envio_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('placa_vehiculo', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.PrimaryKeyConstraint('envio_id')
    )
    op.create_index(op.f('ix_envios_terrestres_bodega_id'), 'envios_terrestres', ['bodega_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envios_terrestres_bodega_id'), table_name='envios_terrestres')
    op.drop_table('envios_terrestres')
    op.drop_index(op.f('ix_envios_maritimos_puerto_id'), table_name='envios_maritimos')
    op.drop_table('envios_maritimos')
    op.drop_index(op.f('ix_envios_tipo_envio'), table_name='envios')
    op.drop_index(op.f('ix_envios_producto_id'), table_name='envios')
    op.drop_index(op.f('ix_envios_numero_guia'), table_name='envios')
    op.drop_index(op.f('ix_envios_eliminado_en'), table_name='envios')
    op.drop_index(op.f('ix_envios_creado_en'), table_name='envios')
    op.drop_index(op.f('ix_envios_cliente_id'), table_name='envios')
    op.drop_table('envios')
    op.drop_index(op.f('ix_puertos_pais'), table_name='puertos')
    op.drop_index(op.f('ix_puertos_nombre'), table_name='puertos')
    op.drop_index(op.f('ix_puertos_eliminado_en'), table_name='puertos')
    op.drop_index(op.f('ix_puertos_creado_en'), table_name='puertos')
    op.drop_table('puertos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_eliminado_en'), table_name='productos')
    op.drop_index(op.f('ix_productos_creado_en'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_eliminado_en'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_creado_en'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_bodegas_pais'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_nombre'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_eliminado_en'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_creado_en'), table_name='bodegas')
    op.drop_table('bodegas')
    # ### end Alembic commands ###
